- name: Copy file to the servers
  become: true
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
  notify: restart_sshd

- handlers:
- name: restart_sshd
  service:
    name: sshd
    state: restarted
