- name: My second playbook
  hosts: all
  gather_facts: true
  vars:
    myvariable: "{{ my_new_value }}"
    myvariablelist:
     - "My Value list 1"
     - "My Value list 2"
     - "My Value list 3"

  tasks:
    - include_role:
        name: role_two_playbook
