- name: Playbook Condition
  template:
    src: mytemplate.j2
    dest: /tmp/mytemplatej2.txt
  when: accion == "instalar" or (ansible_distribution == "Ubuntu" or ansible_distribution_release == "focal")
