- name: Playbook Condition
  template:
    src: mytemplate.j2
    dest: /tmp/mytemplatej2.txt
  when: accion == "Instalar" and (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
